// lib/services/language_service.dart
import 'package:flutter/material.dart';

class LanguageService extends ChangeNotifier {
  Locale _currentLocale = const Locale('en', 'US');
  
  Locale get currentLocale => _currentLocale;
  String get currentLanguage => _currentLocale.languageCode;
  
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'welcome': 'Welcome back! 👋',
      'create_books': 'Create engaging books and lessons for your students',
      'what_you_can_create': 'What you can create',
      'your_books': 'Your Books',
      'create_new': 'Create New',
      'edit': 'Edit',
      'share': 'Share',
      'duplicate': 'Duplicate',
      'delete': 'Delete',
      'dashboard': 'Dashboard',
      'library_class': 'Library / Class',
      'books': 'Books',
      'about_us': 'About Us',
      'feedback': 'Feedback',
      'invite_students': 'Invite Students',
      'language': 'Language',
      'sign_out': 'Sign Out',
      'create_new_book': 'Create New Book',
      'book_creation_coming_soon': 'Book creation wizard coming soon!',
      'close': 'Close',
      'coming_soon': 'Coming Soon',
      'digital_portfolios': 'Digital Portfolios',
      'interactive_lessons': 'Interactive Lessons',
      'storybooks': 'Storybooks',
      'audio_narrations': 'Audio Narrations',
      'science_adventures': 'Science Adventures',
      'math_stories': 'Math Stories',
      'history_chronicles': 'History Chronicles',
      'english_literature': 'English Literature',
      'art_design': 'Art & Design',
      // New About Us translations
      'by_lisatech': 'by LisaTech',
      'our_mission': 'Our Mission',
      'mission_statement': 'Cornerstone connects people through knowledge and transforms classrooms into dynamic learning hubs',
      'get_in_touch': 'Get in Touch',
      'email': 'Email',
      'company_type': 'Company Type',
      'it_company': 'Information Technology Company',
      'follow_us': 'Follow Us',
      'all_rights_reserved': 'All rights reserved',
       'feedback_support': 'Feedback & Support',
  'wed_love_to_hear': 'We\'d Love to Hear From You',
  'share_thoughts': 'Share your thoughts, report bugs, or request features',
  'category': 'Category',
  'general': 'General',
  'bug_report': 'Bug Report',
  'feature_request': 'Feature Request',
  'ui_ux_issue': 'UI/UX Issue',
  'performance': 'Performance',
  'content_issue': 'Content Issue',
  'other': 'Other',
  'your_name': 'Your Name',
  'enter_your_name': 'Enter your name',
  'please_enter_name': 'Please enter your name',
  'email_address': 'Email Address',
  'email_placeholder': 'your.email@example.com',
  'please_enter_email': 'Please enter your email',
  'invalid_email': 'Please enter a valid email',
  'subject': 'Subject',
  'subject_hint': 'Brief description of your feedback',
  'please_enter_subject': 'Please enter a subject',
  'message': 'Message',
  'message_hint': 'Tell us more about your feedback...',
  'please_enter_message': 'Please enter your message',
  'message_too_short': 'Message must be at least 10 characters',
  'submit_feedback': 'Submit Feedback',
  'feedback_submitted': 'Feedback Submitted!',
  'feedback_thank_you': 'Thank you for your feedback. We\'ll review it and get back to you soon!',
  'done': 'Done',
  'failed_submit_feedback': 'Failed to submit feedback',
    },
    'zh': {
      'welcome': '欢迎回来！👋',
      'create_books': '为您的学生创建引人入胜的书籍和课程',
      'what_you_can_create': '您可以创建的内容',
      'your_books': '您的书籍',
      'create_new': '创建新书',
      'edit': '编辑',
      'share': '分享',
      'duplicate': '复制',
      'delete': '删除',
      'dashboard': '仪表板',
      'library_class': '图书馆 / 班级',
      'books': '书籍',
      'about_us': '关于我们',
      'feedback': '反馈',
      'invite_students': '邀请学生',
      'language': '语言',
      'sign_out': '退出登录',
      'create_new_book': '创建新书',
      'book_creation_coming_soon': '图书创建向导即将推出！',
      'close': '关闭',
      'coming_soon': '即将推出',
      'digital_portfolios': '数字作品集',
      'interactive_lessons': '互动课程',
      'storybooks': '故事书',
      'audio_narrations': '音频叙述',
      'science_adventures': '科学冒险',
      'math_stories': '数学故事',
      'history_chronicles': '历史编年史',
      'english_literature': '英国文学',
      'art_design': '艺术与设计',
      // New About Us translations (Chinese)
      'by_lisatech': '由 LisaTech 提供',
      'our_mission': '我们的使命',
      'mission_statement': 'Cornerstone 通过知识连接人们，将教室转变为充满活力的学习中心',
      'get_in_touch': '联系我们',
      'email': '电子邮件',
      'company_type': '公司类型',
      'it_company': '信息技术公司',
      'follow_us': '关注我们',
      'all_rights_reserved': '版权所有',
      'feedback_support': '反馈与支持',
  'wed_love_to_hear': '我们很想听听您的意见',
  'share_thoughts': '分享您的想法、报告错误或请求功能',
  'category': '类别',
  'general': '一般',
  'bug_report': '错误报告',
  'feature_request': '功能请求',
  'ui_ux_issue': '界面/体验问题',
  'performance': '性能',
  'content_issue': '内容问题',
  'other': '其他',
  'your_name': '您的姓名',
  'enter_your_name': '输入您的姓名',
  'please_enter_name': '请输入您的姓名',
  'email_address': '电子邮件地址',
  'email_placeholder': 'your.email@example.com',
  'please_enter_email': '请输入您的电子邮件',
  'invalid_email': '请输入有效的电子邮件',
  'subject': '主题',
  'subject_hint': '简要描述您的反馈',
  'please_enter_subject': '请输入主题',
  'message': '消息',
  'message_hint': '告诉我们更多关于您的反馈...',
  'please_enter_message': '请输入您的消息',
  'message_too_short': '消息必须至少10个字符',
  'submit_feedback': '提交反馈',
  'feedback_submitted': '反馈已提交！',
  'feedback_thank_you': '感谢您的反馈。我们会审核并尽快回复您！',
  'done': '完成',
  'failed_submit_feedback': '提交反馈失败',
    },
  };

  String translate(String key) {
    return _localizedValues[_currentLocale.languageCode]?[key] ?? key;
  }

  void changeLanguage(String languageCode) {
    _currentLocale = Locale(languageCode);
    notifyListeners();
  }

  static final supportedLanguages = [
    {'code': 'en', 'name': 'English'},
    {'code': 'zh', 'name': '中文'},
  ];
}